timeout: 5

/TAEK OS - Modo xHCI Ring 0 (Controlador USB Hardware - Recomendado)
    protocol: limine
    path: boot():/boot/nucleo.elf
    module_path: boot():/boot/video_360p.mp4
    module_cmdline: h264:360p
    cmdline: modo=xhci

/TAEK OS - Benchmark H.264 Forense 360p (FNV-1a 100% Cuadros)
    protocol: limine
    path: boot():/boot/nucleo.elf
    module_path: boot():/boot/video_360p.mp4
    module_cmdline: h264:360p
    cmdline: modo=xhci h264=prueba360

/TAEK OS - Benchmark Rendimiento Pico H.264 360p (Sin Espera PTS)
    protocol: limine
    path: boot():/boot/nucleo.elf
    module_path: boot():/boot/video_360p.mp4
    module_cmdline: h264:360p
    cmdline: modo=xhci h264=bench360

/TAEK OS - Modo Fallback PS/2 Legacy (Teclado Interno)
    protocol: limine
    path: boot():/boot/nucleo.elf
    module_path: boot():/boot/video_360p.mp4
    module_cmdline: h264:360p
    cmdline: modo=ps2
