timeout: 5

/TAEK OS - Modo xHCI Ring 0 (Controlador USB Hardware - Recomendado)
    protocol: limine
    path: boot():/boot/nucleo.elf
    cmdline: modo=xhci

/TAEK OS - Modo Fallback PS/2 Legacy (Teclado Interno)
    protocol: limine
    path: boot():/boot/nucleo.elf
    cmdline: modo=ps2
